### ISSUE TITLE
can't make KRelayBetter to work

### ISSUE THREAD

**Issue by mateogon** [Cursed-Gato/KRelayProxy#1]
couldn't find another way to contact you. I built krelay and ran it, but no proxy server appears in exalt server list. how am I supposed to use this? is it working with latest rotmg version?

**Comment by Cursed-Gato** [comment]
> couldn't find another way to contact you. I built krelay and ran it, but no proxy server appears in exalt server list. how am I supposed to use this? is it working with latest rotmg version?
> 
> I forgot to put In read me Ctrl + f9 to enable disable then join any server from menu

**Comment by mateogon** [comment]
I tried doing that, but when I pres ctrl + f9 nothing happens, and when I join any server, no command from plugins is recognized. are you sure this is how it works?

**Comment by Cursed-Gato** [comment]
Ok so did you put the built DLL into the production, folder of your game, there won't be a proxy server to click on, it just needs to be enabled

**Comment by mateogon** [comment]
ok I didn't do that. what dll do you mean? Lib K Relay.dll?
because I don't see any other dll in the KRelayBetter-main\K_Relay\bin\Release folder.
i placed the lib k relay.dll in production but still nothing works.
Is the building process just building the project in release mode? because if not i'm doing it wrong.

**Comment by Cursed-Gato** [comment]
No the winhttp.dll, you run krelay seperatly, it's in the release section of the repo

**Comment by mateogon** [comment]
ok bro thank you, finally got it working. the command is actually shift + f9 for me :)
